OPENAPI = {
    "openapi": "3.1.0",
    "info": {"title": "Routenda API", "version": "0.1.0"},
    "paths": {
        "/api/v1/requirements": {},
        "/api/v1/requirements/{id}": {},
        "/api/v1/requirements/{id}/revisions": {},
        "/api/v1/requirements/{id}/pause": {},
        "/api/v1/requirements/{id}/contact": {},
        "/api/v1/requirements/{id}/cancel": {},
        "/api/v1/requirements/{id}/resume": {},
        "/api/v1/requirements/{id}/impact-preview": {},
        "/api/v1/agent/intake-sessions": {},
        "/api/v1/agent/messages": {},
        "/api/v1/agent/confirm": {},
        "/api/v1/suppliers": {},
        "/api/v1/suppliers/{id}/sites": {},
        "/api/v1/suppliers/{id}/contacts": {},
        "/api/v1/suppliers/{id}/timeline": {},
        "/api/v1/data-quality": {},
        "/api/v1/master-data-change-requests/{id}/approve": {},
        "/api/v1/master-data-change-requests/{id}/reject": {},
        "/api/v1/availability-polls": {},
        "/api/v1/public/availability/{token}/submit": {},
        "/api/v1/conversations": {},
        "/api/v1/messages": {},
        "/api/v1/inbound-webhook": {},
        "/api/v1/planning/run": {},
        "/api/v1/planning/{id}/result": {},
        "/api/v1/planning/{id}/accept": {},
        "/api/v1/appointments/{id}/confirm": {},
        "/api/v1/appointments/{id}/reschedule": {},
        "/api/v1/appointments/{id}/cancel": {},
        "/api/v1/calendars/sync": {},
        "/api/v1/calendars/conflicts": {},
        "/api/v1/approvals": {},
        "/api/v1/approvals/{id}/approve": {},
        "/api/v1/approvals/{id}/reject": {},
        "/api/v1/audit-events": {},
        "/api/v1/integrations/health": {},
    },
}
